spring:
  data:
    redis:
      host: "redis-13785.c328.europe-west3-1.gce.redns.redis-cloud.com"
      password: "${REDIS_PASSWORD}"
      username: "default"
      port: 13785
      connect-timeout: 5000ms
      timeout: 2000ms

chirp:
  email:
    verification:
      expiry-hours: 24
      cleanup-cron: 0 0 3 * * *
      cleanup-zone: UTC
    reset-password:
      expiry-minutes: 30
      cleanup-cron: 0 0 3 * * *
      cleanup-zone: UTC
