spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

chirp:
  email:
    from: "noreply@vitalijus.lt"
    url: "https://chirp.vitalijus.lt"
