# Notification module configuration
spring:
  rabbitmq:
    host: kebnekaise.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: fnivwunl
    ssl:
      enabled: true
    virtual-host: fnivwunl
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enable: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2