spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

chirp:
  email:
    from: "vitalikas@yopmail.com"
    url: "http://localhost:${server.port}"
